import React from 'react';
import { Droplets, Sprout, Ruler, Wrench, IndianRupee, ShieldCheck, ArrowUpRight } from 'lucide-react';
import { Badge, SectionHeading, ReadAloud } from '../ui/Primitives';
import { money } from '../../utils/format';
import PlanVisual from './PlanVisual';

export function PlotSummary({ plot }) { return <div className="planner-summary"><div><span>Approximate area</span><strong>{plot.area_acres} acres</strong><small>{plot.area_sq_m} m² · {plot.area_cents} cents · {plot.area_hectares} ha</small></div><div><span>Shape read</span><strong>{plot.shape_type}</strong><small>{plot.perimeter_m ? `${plot.perimeter_m} m boundary` : 'From your marked boundary'}</small></div><div><span>Planning area</span><strong>{plot.usable_area_sq_m || Math.round(plot.area_sq_m * .93)} m²</strong><small>Approx. 7% allowance for access and edge space</small></div></div>; }
export function CoconutCard({ layout }) { return <section className="planner-card coconut-card"><div className="planner-card-heading"><span className="planner-icon olive"><Sprout size={24}/></span><div><div className="eyebrow">PLANTATION LAYOUT</div><h2>A considered start for coconut</h2></div></div><div className="planner-stat-row"><div><Ruler size={17}/><strong>{layout.spacing_x_m} × {layout.spacing_y_m} m</strong><span>recommended spacing</span></div><div><Sprout size={17}/><strong>{layout.estimated_tree_count}</strong><span>approx. trees</span></div><div><span className="row-glyph">▦</span><strong>{layout.row_count} rows</strong><span>estimated rows</span></div></div><p className="planner-note">A {layout.boundary_buffer_m} m boundary buffer leaves room to access trees and maintain the edge.</p><small className="source-note">{layout.rule_note}</small></section>; }
export function IrrigationCard({ irrigation }) { return <section className="planner-card"><div className="planner-card-heading"><span className="planner-icon blue"><Droplets size={24}/></span><div><div className="eyebrow">WATER PLAN</div><h2>{irrigation.recommended_method}</h2></div><Badge tone={irrigation.recommended_method.startsWith('Water') ? 'amber' : 'green'}>{irrigation.recommended_method.startsWith('Water') ? 'Verify first' : 'Planning recommendation'}</Badge></div><p className="planner-lead">{irrigation.reason}</p><ReadAloud text={irrigation.reason}/><div className="material-mini"><span><strong>{irrigation.main_pipe_length_m} m</strong>Main pipe</span><span><strong>{irrigation.lateral_length_m} m</strong>Lateral pipe</span><span><strong>{irrigation.dripper_count || '—'}</strong>Drippers</span><span><strong>{irrigation.filter_required ? '1' : '—'}</strong>Filter</span></div></section>; }
export function IntercropCard({ crops }) { return <section className="planner-card"><div className="planner-card-heading"><span className="planner-icon gold"><Sprout size={24}/></span><div><div className="eyebrow">POSSIBLE EXTRA-INCOME OPTIONS</div><h2>What could grow between the rows?</h2></div></div><div className="intercrop-list">{crops.map((crop,i)=><div key={crop.crop_name}><span className="intercrop-number">0{i+1}</span><div><h3>{crop.crop_name} <Badge tone="neutral">{crop.suitability_level}</Badge></h3><p>{crop.reason}</p><small>Water: {crop.water_requirement} · Labour: {crop.labour_requirement}</small></div></div>)}</div><p className="planner-note">Intercrops are possibilities, not guaranteed income. Confirm sunlight, drainage, season and market with a local expert.</p></section>; }
export function MaterialsCard({ materials, cost }) { return <section className="planner-card"><div className="planner-card-heading"><span className="planner-icon brown"><Wrench size={24}/></span><div><div className="eyebrow">ROUGH MATERIAL ESTIMATE</div><h2>What the setup may need</h2></div></div><div className="materials-table">{materials.map(item=><div key={item.item_name}><span>{item.item_name}</span><strong>{item.quantity} {item.unit}</strong><small>{money(item.estimated_low_cost)} – {money(item.estimated_high_cost)}</small></div>)}</div><div className="cost-band"><IndianRupee size={19}/><div><span>Estimated total range</span><strong>{money(cost.low)} – {money(cost.high)}</strong></div></div><small className="source-note">Actual cost changes with brand, pipe quality, labour, pump requirement and local availability.</small></section>; }
export function TrustCard({ status, onReview }) { return <section className="trust-card"><ShieldCheck size={25}/><div><div className="eyebrow">BEFORE YOU SPEND</div><h3>Field verification is part of the plan.</h3><p>This is a preliminary estimate, not a legal survey or final engineering design.</p></div>{status === 'Generated' || status === 'Changes Requested' ? <button className="text-link" onClick={onReview}>Request officer review <ArrowUpRight size={16}/></button> : <Badge tone={status === 'Approved' ? 'green' : 'amber'}>{status}</Badge>}</section>; }
