import React from 'react';
import { ArrowUpDown, Store } from 'lucide-react';
import RefreshButton from '../common/RefreshButton';
import LastUpdatedText from '../common/LastUpdatedText';
import PriceChangeBadge from './PriceChangeBadge';
import { useLanguage } from '../../i18n/languageContext';
import { cropLabels } from '../../i18n/translations';
const crops = ['banana','coconut','paddy','pepper','tomato','onion','potato','arecanut','rubber','ginger','turmeric','vegetables'];
export default function MarketPriceCard({ data, loading, onRefresh, crop = 'banana', onCropChange }) { const { t, language } = useLanguage(); const cropLabel = key => cropLabels[language]?.[key] || cropLabels.en[key] || key; if (loading && !data) return <section className="live-card"><div className="eyebrow">{t('market')}</div><p>{t('loadingPrices') || 'Loading market prices…'}</p></section>; if (!data) return null; return <section className="live-card market-live-card"><div className="live-card-head"><div><div className="eyebrow">{t('market')}</div><h2>{t('marketTitle')}</h2><p className="live-location"><Store size={14}/> {cropLabel(crop)} · {data.market}, {data.district}</p></div><RefreshButton onClick={onRefresh} busy={loading}/></div><label className="market-crop-select">{t('selectCrop') || 'Select crop'}<select value={crop} onChange={e => onCropChange?.(e.target.value)}>{crops.map(key => <option key={key} value={key}>{cropLabel(key)}</option>)}</select></label><div className="price-grid"><div><span>{t('minimum') || 'Minimum'}</span><strong>₹{data.min_price}</strong><small>/ {t('quintal') || 'quintal'}</small></div><div><span>{t('maximum') || 'Maximum'}</span><strong>₹{data.max_price}</strong><small>/ {t('quintal') || 'quintal'}</small></div><div className="modal-price"><span>{t('modal') || 'Modal'}</span><strong>₹{data.modal_price}</strong><small>/ {t('quintal') || 'quintal'}</small></div></div><div className="price-suggestion"><ArrowUpDown size={17}/><p><strong><PriceChangeBadge change={data.change} direction={data.change_direction}/></strong><br/>{data.suggestion}</p></div><LastUpdatedText value={data.updated_at} warning={data.warning}/></section>; }
