import React, { useState } from 'react';
import { Plus, ArrowDownLeft, ArrowUpRight, Download } from 'lucide-react';
import { PageHeading, Button, Modal, Field, Empty } from '../components/ui/Primitives';
import { workspaceAPI } from '../services/workspace';
import { money, prettyDate, today } from '../utils/format';

export default function CashbookPage({ entries, mutate, staff }) {
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[crop,setCrop]=useState('All crops');
  const rows=entries.filter(e=>crop==='All crops'||e.crop===crop);
  const total=kind=>rows.filter(e=>e.kind===kind).reduce((a,e)=>a+e.amount,0);
  async function save(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);const ok=await mutate(()=>workspaceAPI.create('cashbook',{...data,amount:Number(data.amount)}),'Entry added to your cashbook.');setBusy(false);if(ok)setOpen(false);}
  function download(){const quote=v=>`"${String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const csv=['Date,Crop,Type,Category,Amount,Note',...rows.map(e=>[e.date,e.crop,e.kind,e.category,e.amount,e.note].map(quote).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='krishi-cashbook.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <><PageHeading eyebrow="KNOW WHAT GOES IN. KNOW WHAT COMES BACK." title={<>Make every <em>rupee count.</em></>} description="A simple record of farm spending and sales. Your numbers, clearly." action={!staff && <Button onClick={()=>setOpen(true)}><Plus size={17}/> Add an entry</Button>}/><div className="cash-summary"><div><span>Recorded income</span><strong>{money(total('Income'))}</strong><small>Money received</small></div><div><span>Recorded expenses</span><strong>{money(total('Expense'))}</strong><small>Money spent</small></div><div className="balance"><span>Recorded balance</span><strong>{money(total('Income')-total('Expense'))}</strong><small>Income less recorded expenses</small></div></div><p className="muted small">This is a cash balance, not a complete profit calculation. Unrecorded costs, inventory and unpaid sales are not included.</p><div className="table-toolbar"><h2>Your entries</h2><select aria-label="Filter by crop" value={crop} onChange={e=>setCrop(e.target.value)}><option>All crops</option>{[...new Set(entries.map(e=>e.crop))].map(c=><option key={c}>{c}</option>)}</select><Button variant="secondary" onClick={download}><Download size={16}/> Export CSV</Button></div><div className="table-scroll"><table><thead><tr><th>Entry</th><th>Crop</th><th>Date</th><th>Type</th><th className="number">Amount</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><strong>{e.category}</strong><small>{e.note}</small></td><td>{e.crop}</td><td>{prettyDate(e.date)}</td><td><span className={`flow-label ${e.kind==='Income'?'income':''}`}>{e.kind==='Income'?<ArrowDownLeft size={15}/>:<ArrowUpRight size={15}/>} {e.kind}</span></td><td className="number"><strong>{money(e.amount)}</strong></td></tr>)}</tbody></table></div>{!rows.length && <Empty title="A fresh page in your cashbook">Add the first expense or sale to begin.</Empty>}{open && <Modal title="Add a cashbook entry" onClose={()=>setOpen(false)}><form onSubmit={save}><div className="form-grid"><Field label="Type"><select name="kind"><option>Expense</option><option>Income</option></select></Field><Field label="Amount in rupees"><input name="amount" type="number" min="0.01" max="100000000" step="0.01" required/></Field></div><div className="form-grid"><Field label="Crop"><input name="crop" placeholder="Paddy" minLength={2} required/></Field><Field label="Date"><input name="date" type="date" defaultValue={today()} required/></Field></div><Field label="Category"><input name="category" placeholder="Seed, labour, harvest sale…" minLength={2} required/></Field><Field label="Note (optional)"><input name="note" maxLength={500}/></Field><Button disabled={busy}>{busy?'Saving…':'Save entry'}</Button></form></Modal>}</>;
}
