import React, { useEffect, useState } from 'react';
import { Plus, ShieldCheck } from 'lucide-react';
import { PageHeading, Button, Badge, Modal, Field, Empty } from '../components/ui/Primitives';
import { apiCall } from '../services/api';
import { prettyDate } from '../utils/format';
const boards=['Paddy','Banana','Coconut','Pepper','Machinery','Market','Schemes'];

export default function CommunityPage({ staff }) {
  const [posts,setPosts]=useState([]),[board,setBoard]=useState('All boards'),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{try{setPosts(await apiCall('/community'));setError('');}catch(e){setError(e.message);}};
  useEffect(()=>{load();},[]);
  async function create(e){e.preventDefault();const value=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await apiCall('/community','POST',value);setOpen(false);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const moderate=async(id,status)=>{setBusy(true);try{await apiCall(`/community/${id}`,'PATCH',{status});await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const shown=posts.filter(p=>board==='All boards'||p.board===board);
  return <><PageHeading eyebrow="KNOWLEDGE GROWS WHEN IT IS SHARED" title={<>From one farmer <em>to another.</em></>} description="Practical experiences and local notices. Every post passes through moderation." action={<Button onClick={()=>setOpen(true)}><Plus size={17}/> Share a note</Button>}/><div className="info-box"><ShieldCheck size={22}/><p>Farmer experiences are personal observations, not verified treatment advice. Use Crop care for a problem that needs an expert review.</p></div>{error&&!open&&<div className="form-error" role="alert">{error}<button className="text-link" onClick={load}>Retry</button></div>}<div className="tabs">{['All boards',...boards].map(b=><button className={b===board?'selected':''} key={b} onClick={()=>setBoard(b)}>{b}</button>)}</div><div className="group-list">{shown.map(p=><article className="group-card" key={p.id}><div className="group-top"><Badge tone="olive">{p.board} · {p.label}</Badge><Badge tone={p.status==='Published'?'green':'amber'}>{p.status}</Badge></div><h2>{p.title}</h2><p style={{whiteSpace:'pre-wrap'}}>{p.body}</p><div className="group-footer"><span>{p.author} · {prettyDate(p.created_at)}</span>{staff&&<div className="row-actions"><Button disabled={busy||p.status==='Published'} variant="secondary" onClick={()=>moderate(p.id,'Published')}>Publish</Button><button className="text-link danger" disabled={busy||p.status==='Not published'} onClick={()=>moderate(p.id,'Not published')}>Withhold</button></div>}</div></article>)}</div>{!shown.length&&<Empty title="A good conversation starts somewhere">Share an experience or a useful local notice. Your post becomes visible to others after moderation.</Empty>}{open&&<Modal title="Share a useful note" subtitle="Avoid personal contact details and unverified treatment instructions." onClose={()=>setOpen(false)}><form onSubmit={create}><Field label="Board"><select name="board">{boards.map(b=><option key={b}>{b}</option>)}</select></Field><Field label="Title"><input name="title" minLength={5} maxLength={120} required/></Field><Field label="Your experience or notice"><textarea name="body" minLength={20} maxLength={3000} rows={5} required/></Field>{error&&<div className="form-error" role="alert">{error}</div>}<Button disabled={busy}>{busy?'Saving…':'Send for moderation'}</Button></form></Modal>}</>;
}
