import React, { useState } from 'react';
import { Plus, ArrowUpRight, Clock, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { PageHeading, Button, Badge, Empty } from '../components/ui/Primitives';
import { prettyDate } from '../utils/format';

export default function CropCarePage({ reports, staff, onReport, onCase }) {
  const [filter, setFilter] = useState('All reports');
  const shown = reports.filter(c => filter === 'All reports' || (filter === 'Waiting for review' ? c.status === 'Awaiting Officer Review' : filter === 'Reviewed' ? c.status === 'Officer Verified' : c.status === 'Closed'));
  return <><PageHeading eyebrow={staff ? 'THE EXPERT DESK' : 'A LITTLE HELP GOES A LONG WAY'} title={staff ? <>Good advice starts <em>with listening.</em></> : <>Care for what <em>you grow.</em></>} description={staff ? 'Review farmer observations, share guidance, and close the loop.' : 'Report a concern. Hear from an expert. Keep track of what comes next.'} action={!staff && <Button onClick={onReport}><Plus size={17}/> Report a crop problem</Button>}/><div className="metric-grid"><div><Clock size={22}/><strong>{reports.filter(r=>r.status==='Awaiting Officer Review').length}</strong><span>Waiting for review</span></div><div><ShieldCheck size={22}/><strong>{reports.filter(r=>r.status==='Officer Verified').length}</strong><span>Reviewed guidance</span></div><div><CheckCircle2 size={22}/><strong>{reports.filter(r=>r.status==='Closed').length}</strong><span>Issues resolved</span></div></div><div className="tabs">{['All reports','Waiting for review','Reviewed','Resolved'].map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v}</button>)}</div><div className="report-list">{shown.map(c=><button className="report-card" key={c.id} onClick={()=>onCase(c)}><span className="report-letter">{c.crop_type.slice(0,1)}</span><div className="report-main"><div className="eyebrow">{c.case_number} · {prettyDate(c.created_at)}</div><h3>{c.crop_type} · {c.field_location}</h3><p>{c.symptoms_description}</p>{staff && <small>From {c.farmer_name}</small>}</div><Badge tone={c.status==='Closed'?'neutral':c.officer_review?'green':'amber'}>{c.status==='Awaiting Officer Review'?'Waiting for review':c.status}</Badge><ArrowUpRight size={20}/></button>)}</div>{!shown.length && <Empty title="Nothing here just yet">Your crop reports and expert responses will appear here.</Empty>}</>;
}
