import React, { useState } from 'react';
import { Plus, Sprout, Droplets, CalendarDays, ArrowUpRight } from 'lucide-react';
import { PageHeading, Button, Modal, Field, Badge, Empty } from '../components/ui/Primitives';
import { workspaceAPI } from '../services/workspace';
import { prettyDate, today } from '../utils/format';

export default function FarmPage({ plots, mutate, onReport }) {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  async function save(e) {
    e.preventDefault(); const fields = Object.fromEntries(new FormData(e.currentTarget)); setBusy(true);
    const ok = await mutate(() => workspaceAPI.create('plots', { ...fields, area: Number(fields.area) }), 'Your plot is ready.');
    setBusy(false); if (ok) setOpen(false);
  }
  return <><PageHeading eyebrow="YOUR LAND, AT A GLANCE" title={<>Every plot has <em>a story.</em></>} description="Keep each crop, season and growing stage in one place." action={<Button onClick={() => setOpen(true)}><Plus size={17}/> Add a plot</Button>}/><div className="summary-line"><span><strong>{plots.length}</strong> plots</span><span><strong>{plots.reduce((a,p) => a+p.area,0).toFixed(1)}</strong> acres recorded</span><span><strong>{new Set(plots.map(p=>p.crop)).size}</strong> crops growing</span></div><div className="card-grid">{plots.map((p,i) => <article className="plot-card" key={p.id}><div className={`plot-art crop-${i%3}`}><Sprout size={70} strokeWidth={1}/><span>{String(i+1).padStart(2,'0')}</span><Badge>{p.area} acres</Badge></div><div className="card-body"><div className="eyebrow">{p.name}</div><h2>{p.crop}</h2><Badge tone="green">{p.growth_stage}</Badge><div className="detail-lines"><span><Droplets size={17}/>{p.water_source}</span><span><CalendarDays size={17}/>Planted {prettyDate(p.planting_date)}</span></div><button className="text-link" onClick={onReport}>Ask about this crop <ArrowUpRight size={16}/></button></div></article>)}</div>{!plots.length && <Empty title="Let’s start with your first plot">Add a name you recognise, your crop and its planting date.</Empty>}{open && <Modal title="Add a farm plot" subtitle="A few details make your farm records more useful." onClose={() => setOpen(false)}><form onSubmit={save}><Field label="Plot name"><input name="name" placeholder="e.g. Canal-side field" required minLength={2} maxLength={100}/></Field><div className="form-grid"><Field label="Crop"><select name="crop">{['Paddy','Banana','Coconut','Pepper','Vegetables','Other'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Area in acres"><input name="area" type="number" min="0.01" step="0.01" required/></Field></div><Field label="Planting date"><input name="planting_date" type="date" max={today()} required/></Field><div className="form-grid"><Field label="Irrigation source"><select name="water_source">{['Canal','Well','Borewell','Rain-fed','Pond'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Crop stage"><select name="growth_stage">{['initial','vegetative','flowering','fruiting','maturity'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Button disabled={busy}>{busy ? 'Saving…' : 'Save plot'}</Button></form></Modal>}</>;
}
