import React, { useState } from 'react';
import { ArrowUpRight, Files, Check, ShieldCheck, Landmark } from 'lucide-react';
import { PageHeading, Badge, Button } from '../components/ui/Primitives';
import { workspaceAPI } from '../services/workspace';

export function SchemesPage({ schemes, navigate }) {
  const [crop,setCrop]=useState('All crops');
  const matches=schemes.filter(s=>crop==='All crops'||s.crop_category?.toLowerCase().includes(crop.toLowerCase()));
  return <><PageHeading eyebrow="SUPPORT, WITHOUT THE RUNAROUND" title={<>Find your <em>next opportunity.</em></>} description="Understand what a scheme asks for before you start an application."/><div className="notice-strip">Sample scheme catalogue · Eligibility, amounts and deadlines require verification on the official portal. These are not approval decisions.</div><div className="table-toolbar"><h2>Explore by crop</h2><select aria-label="Filter schemes by crop" value={crop} onChange={e=>setCrop(e.target.value)}><option>All crops</option>{[...new Set(schemes.map(s=>s.crop_category).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></div><div className="scheme-list">{matches.map(s=><article className="scheme-card" key={s.id}><span className="scheme-icon"><Landmark size={25}/></span><div><Badge tone="neutral">Sample · {s.crop_category}</Badge><h2>{s.name}</h2><p>{s.eligibility_criteria}</p><details><summary>Documents to prepare</summary><p>{s.required_documents}</p></details><button className="text-link" onClick={()=>navigate('documents')}>Open my checklist <ArrowUpRight size={16}/></button></div></article>)}</div><div className="official-link"><div><h3>Check current official schemes</h3><p>myScheme helps you find relevant programmes and their application pages.</p></div><a className="button primary" href="https://www.myscheme.gov.in/" target="_blank" rel="noreferrer">Visit myScheme <ArrowUpRight size={17}/></a></div></>;
}

const documents=['Identity proof','Land record','Bank details','Crop insurance','Application receipt'];
export function DocumentsPage({ available, mutate, staff }) {
  const [busy,setBusy]=useState(false);
  return <><PageHeading eyebrow="A LITTLE PREPARATION GOES A LONG WAY" title={<>Your documents. <em>In order.</em></>} description="Keep a checklist of what you have, and what you still need."/><div className="info-box"><ShieldCheck size={24}/><p>This is a readiness checklist. It does not upload, store or verify your identity documents. Keep originals secure; authorised DigiLocker integration is planned.</p></div><div className="document-progress"><strong>{available.length} of {documents.length} ready</strong><div><span style={{width:`${available.length/documents.length*100}%`}}/></div></div><div className="document-list">{documents.map((name,i)=><article key={name}><span className="document-index">0{i+1}</span><Files size={25}/><div><h3>{name}</h3><p>{['Accepted proof depends on the scheme.','Ownership or tenancy evidence, as applicable.','Account proof for the relevant application.','Policy and claim references, if insured.','Acknowledgement for submitted applications.'][i]}</p></div><button disabled={busy||staff} aria-pressed={available.includes(name)} className={`check-toggle ${available.includes(name)?'checked':''}`} onClick={async()=>{setBusy(true);await mutate(()=>workspaceAPI.document(name),'Checklist updated.');setBusy(false);}}>{available.includes(name)?<><Check size={16}/> Ready</>:'Mark ready'}</button></article>)}</div><a className="text-link" href="https://www.digilocker.gov.in/" target="_blank" rel="noreferrer">Open official DigiLocker <ArrowUpRight size={16}/></a></>;
}
