import React, { useCallback, useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, CloudSun, Droplets, Wind, Sprout, Camera, Tractor, Check, Users, Sun, CalendarDays, ShieldCheck, ChevronRight } from 'lucide-react';
import { PageHeading, SectionHeading, Badge, ReadAloud, Empty } from '../components/ui/Primitives';
import { firstName, prettyDate } from '../utils/format';
import { liveDataAPI } from '../services/liveDataApi';
import useAutoRefresh from '../hooks/useAutoRefresh';
import WeatherCard from '../components/weather/WeatherCard';
import MarketPriceCard from '../components/market/MarketPriceCard';

function FieldArtwork() {
  return <svg className="field-art" viewBox="0 0 530 340" fill="none" aria-hidden="true"><circle cx="377" cy="78" r="45" fill="#E9C985"/><path d="M-20 250C90 99 225 124 551 223V365H-20Z" fill="#799471"/><path d="M-10 282C151 205 355 175 553 135V370H-10Z" fill="#B4BE86"/><path d="M30 353C153 270 334 268 553 245V360" fill="#D9D0A4"/>{[0,1,2,3,4,5].map(i=><path key={i} d={`M${-55+i*55} 355C${100+i*39} 243 ${260+i*25} 249 551 ${175+i*16}`} stroke="#F1E8C8" strokeWidth="2" opacity=".6"/>)}<path d="M-20 253C150 116 256 149 408 190" stroke="#C2D0AE" strokeWidth="2"/>{[0,1,2,3].map(i=><path key={i} d={`M${40+i*20} 241L${66+i*20} 224M${75+i*24} 221L${104+i*24} 207`} stroke="#CCD8B2" strokeWidth="2"/>)}<path d="M327 175V126L352 106L378 126V185" fill="#EDE7CF"/><path d="M319 128L352 99L386 128" fill="#A06D4C"/><path d="M348 181V150H360V184" fill="#596D52"/><path d="M426 158V95M426 111C394 120 397 84 426 96M426 112C460 112 448 82 426 96" stroke="#425B41" strokeWidth="5"/><path d="M484 144V94M484 111C456 110 463 83 484 96M484 114C511 110 507 88 484 96" stroke="#425B41" strokeWidth="4"/></svg>;
}

export default function TodayPage({ user, data, navigate, onReport, onCase }) {
  const [weather, setWeather] = useState(null), [market, setMarket] = useState(null), [liveLoading, setLiveLoading] = useState(true), [marketCrop, setMarketCrop] = useState(localStorage.getItem('preferredMarketCrop') || 'banana');
  const loadLive = useCallback(async (initial = false) => { if (initial) setLiveLoading(true); try { const [nextWeather, nextMarket] = await Promise.all([liveDataAPI.farmerWeather(user.id), liveDataAPI.market({ commodity: marketCrop, state: 'Kerala', district: 'Thrissur' })]); setWeather(nextWeather); setMarket(nextMarket); } catch { setWeather(previous => previous || { location: { name: 'Palakkad, Kerala' }, temperature_c: 29, condition: 'Pilot fallback', rain_chance: 60, humidity: 82, wind_kmh: 8, action: 'Rain may arrive today. Avoid pesticide spraying until conditions are clear.', updated_at: new Date().toISOString(), warning: 'Showing pilot fallback data.' }); setMarket(previous => previous || { commodity: marketCrop, market: 'Thrissur', district: 'Thrissur', min_price: 2800, max_price: 3400, modal_price: 3100, change: 150, change_direction: 'up', suggestion: 'Price has improved. Check group selling options.', updated_at: new Date().toISOString(), warning: 'Showing pilot fallback data.' }); } finally { if (initial) setLiveLoading(false); } }, [user.id, marketCrop]);
  useEffect(() => { loadLive(true); }, [loadLive]); useAutoRefresh(() => loadLive(false), 60000);
  const verified = data.cases.find(c => c.officer_review && c.status !== 'Closed');
  const pending = data.cases.filter(c => c.status === 'Awaiting Officer Review');
  const date = new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' });
  const tasks = [
    verified && { type:'EXPERT ADVICE', title:`Your ${verified.crop_type.toLowerCase()} report has a response`, text: 'Read the reviewed guidance and plan your next step.', icon: ShieldCheck, action: 'Read advice', click: () => onCase(verified), tone:'green' },
    { type: 'FARM RECORD', title: data.plots.length ? 'A little observation goes a long way' : 'Let’s get to know your first plot', text: data.plots.length ? 'Keep your crop stage and field notes close at hand.' : 'Add your crop, planting date and irrigation source.', icon: Sprout, action: 'Open my farm', click: () => navigate('farm'), tone:'olive' },
    { type:'PLAN AHEAD', title: 'Need a hand for the next farm job?', text: 'Request equipment or coordinate a shared service.', icon: Tractor, action: 'Find a service', click: () => navigate('resources'), tone:'sand' },
  ].filter(Boolean);
  return <>
    <PageHeading eyebrow={date} title={<>A good day starts here, <em>{firstName(user.full_name)}.</em></>} description="A little clarity for your farm. One useful step at a time." action={<button className="button secondary compact" onClick={() => navigate('farm')}><Sprout size={17}/> My farm <ArrowUpRight size={16}/></button>}/>
    <div className="today-layout"><div className="today-main">
      <section className="season-banner"><div className="season-copy"><div className="eyebrow">ROOTED IN THE EVERYDAY</div><h2>Your land.<br/>A season of possibility.</h2><p>From the first seed to the next harvest,<br/>keep your next step in sight.</p><button className="banner-link" onClick={() => navigate('farm')}>Walk through your farm <ArrowRight size={18}/></button></div><FieldArtwork/><span className="season-stamp"><Sprout size={14}/> GROW WITH CONFIDENCE</span></section>
      <section className="daily-section"><SectionHeading title="Your next steps" action="View farm" onClick={() => navigate('farm')}/><p className="section-subtitle">The things that deserve your attention.</p><div className="action-list">{tasks.map((task, i) => <article className="action-row" key={task.type}><span className="step-number">0{i+1}</span><span className={`action-icon ${task.tone}`}><task.icon size={22}/></span><div className="action-copy"><div className="eyebrow">{task.type}</div><h3>{task.title}</h3><p>{task.text}</p></div><button className="action-button" onClick={task.click} aria-label={task.action}><ArrowUpRight size={21}/></button></article>)}</div></section>
      <section><SectionHeading title="Growing on your farm" action="All plots" onClick={() => navigate('farm')}/><div className="plot-strip">{data.plots.slice(0,3).map((plot, i) => <button className={`mini-plot crop-${i}`} key={plot.id} onClick={() => navigate('farm')}><div className="mini-plot-top"><Sprout size={21}/><ArrowUpRight size={16}/></div><h3>{plot.crop}</h3><p>{plot.name} · {plot.area} acres</p><div className="plot-stage"><span/> {plot.growth_stage}</div></button>)}{!data.plots.length && <Empty title="Your story starts with a plot">Add your first plot to personalise this space.</Empty>}</div></section>
      <section className="community-banner"><span className="community-icon"><Users size={30}/></span><div><div className="eyebrow">BETTER, TOGETHER</div><h3>Small farms. Shared possibilities.</h3><p>Share a tractor, a market trip, or the work ahead.</p></div><button className="round-button" onClick={() => navigate('groups')} aria-label="Explore cooperation"><ArrowUpRight/></button></section>
    </div><aside className="today-rail">
      <WeatherCard data={weather} loading={liveLoading} onRefresh={() => loadLive(false)}/><MarketPriceCard data={market} crop={marketCrop} onCropChange={value => { localStorage.setItem('preferredMarketCrop', value); setMarketCrop(value); }} loading={liveLoading} onRefresh={() => loadLive(false)}/>
      <section className="help-panel"><span className="outlined-icon"><Camera size={24}/></span><h3>Something doesn’t<br/>look right?</h3><p>Share a photo of your crop.<br/>An expert can help you find<br/>the next step.</p><button className="button primary" onClick={onReport}>Report a crop problem <ArrowUpRight size={16}/></button><small><ShieldCheck size={13}/> Guidance reviewed by a person</small></section>
      <section className="rail-requests"><SectionHeading title="In progress"/>{pending.length ? pending.slice(0,2).map(c => <button key={c.id} className="request-peek" onClick={() => onCase(c)}><span className="status-dot"/><div><strong>{c.crop_type} crop report</strong><small>Waiting for expert review</small></div><ChevronRight size={16}/></button>) : <p className="muted">No crop reports waiting for review.</p>}{data.bookings.filter(b => !['Cancelled','Completed'].includes(b.status)).slice(0,2).map(b => <button className="request-peek" key={b.id} onClick={() => navigate('resources')}><CalendarDays size={16}/><div><strong>{b.resource_name}</strong><small>{prettyDate(b.date)} · {b.status}</small></div></button>)}</section>
    </aside></div>
  </>;
}
