import React, { useEffect, useRef, useState } from 'react';
import { Mic, Send, Square, X } from 'lucide-react';
import { askAssistant, createRecognition, speak } from '../../services/voiceAssistantService';
import { useLanguage } from '../../i18n/languageContext';
import VoiceAssistantButton from './VoiceAssistantButton';
export default function VoiceAssistantPanel() { const { language, t } = useLanguage(); const [open, setOpen] = useState(false), [listening, setListening] = useState(false), [query, setQuery] = useState(''), [transcript, setTranscript] = useState(''), [answer, setAnswer] = useState(''); const recognition = useRef(null);
  useEffect(() => () => recognition.current?.stop(), []);
  const ask = async text => { if (!text.trim()) return; setTranscript(text); try { const result = await askAssistant(text, language); setAnswer(result.reply); speak(result.reply, language); if (result.intent?.startsWith('input_guard')) location.hash = 'input-guard'; } catch { setAnswer('I could not reach the assistant. You can try again.'); } };
  const listen = () => { recognition.current = createRecognition(language, text => { setListening(false); setQuery(text); ask(text); }, () => setListening(false), () => setListening(false)); if (!recognition.current) return setAnswer('Voice recognition is not supported for this language on your browser. You can type your question instead.'); setListening(true); recognition.current.start(); };
  return <>{open && <div className="voice-panel"><div className="voice-panel-head"><div><div className="eyebrow">{t('voice')}</div><h2>Simple answers for the next step</h2></div><button className="icon-button" onClick={() => setOpen(false)}><X size={18}/></button></div><p className="voice-language">{t('language')}: {language.toUpperCase()} · Ask about weather, banana price, schemes or tractors.</p>{transcript && <div className="voice-transcript"><span>You asked</span><p>{transcript}</p></div>}{answer && <div className="voice-answer"><span>Krishi Sahayak</span><p>{answer}</p></div>}<form onSubmit={e => { e.preventDefault(); ask(query); }} className="voice-input"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Type: weather or banana price"/><button><Send size={17}/></button></form><div className="voice-controls"><button className="button primary" onClick={listen} disabled={listening}>{listening ? <><Mic size={16}/> {t('listening')}</> : <><Mic size={16}/> Speak</>}</button>{listening && <button className="button secondary" onClick={() => { recognition.current?.stop(); setListening(false); }}><Square size={14}/> Stop</button>}</div><small className="voice-note">Voice support depends on your browser. Typed questions always remain available.</small></div>}<VoiceAssistantButton onClick={() => setOpen(!open)}/></>;
}
