export const cropKeys = ['banana','coconut','paddy','pepper','tomato','onion','potato','arecanut','rubber','ginger','turmeric','vegetables'];
export const translations = {
  en: { language: 'Language', weatherTitle: 'Weather for your farm', marketTitle: 'Crop price', refresh: 'Refresh', lastUpdated: 'Last updated', rainWarning: 'Avoid pesticide spraying today.', weather: 'Weather', market: 'Market watch', voice: 'Ask Krishi Sahayak', listening: 'Listening…', loadingPrices:'Loading market prices…', selectCrop:'Select crop', minimum:'Minimum', maximum:'Maximum', modal:'Modal', quintal:'quintal', nav_today:'Today', nav_farm:'My farm', nav_help:'Crop care', nav_resources:'Farm services', nav_groups:'Together', nav_market:'Market watch', nav_planner:'Smart Farm Planner', nav_cashbook:'Cashbook', nav_schemes:'Schemes & support', nav_documents:'My documents', nav_community:'Community' },
  ml: { language: 'ഭാഷ', weatherTitle: 'നിങ്ങളുടെ കൃഷിയിടത്തിലെ കാലാവസ്ഥ', marketTitle: 'വിള വില', refresh: 'പുതുക്കുക', lastUpdated: 'അവസാനം പുതുക്കിയത്', rainWarning: 'ഇന്ന് കീടനാശിനി തളിക്കുന്നത് ഒഴിവാക്കുക.', weather: 'കാലാവസ്ഥ', market: 'മാർക്കറ്റ് വാച്ച്', voice: 'കൃഷി സഹായകിനോട് ചോദിക്കുക', listening: 'കേൾക്കുന്നു…', nav_today:'ഇന്ന്', nav_farm:'എന്റെ കൃഷിയിടം', nav_help:'വിള പരിചരണം', nav_resources:'കൃഷി സേവനങ്ങൾ', nav_groups:'ഒരുമിച്ച്', nav_market:'വിപണി', nav_planner:'സ്മാർട്ട് ഫാം പ്ലാനർ' },
  hi: { language: 'भाषा', weatherTitle: 'आपके खेत का मौसम', marketTitle: 'फसल भाव', refresh: 'रिफ्रेश', lastUpdated: 'अंतिम अपडेट', rainWarning: 'आज कीटनाशक का छिड़काव न करें।', weather: 'मौसम', market: 'मार्केट वॉच', voice: 'कृषि सहायक से पूछें', listening: 'सुन रहा है…', nav_today:'आज', nav_farm:'मेरा खेत', nav_help:'फसल देखभाल', nav_resources:'कृषि सेवाएं', nav_groups:'साथ मिलकर', nav_market:'बाज़ार', nav_planner:'स्मार्ट फार्म प्लानर' },
  ta: { language: 'மொழி', weatherTitle: 'உங்கள் பண்ணையின் வானிலை', marketTitle: 'பயிர் விலை', refresh: 'புதுப்பிக்கவும்', lastUpdated: 'கடைசியாக புதுப்பித்தது', rainWarning: 'இன்று பூச்சிக்கொல்லி தெளிப்பதை தவிர்க்கவும்.', weather: 'வானிலை', market: 'மார்க்கெட் வாட்ச்', voice: 'கிருஷி சகாயக்கிடம் கேளுங்கள்', listening: 'கேட்கிறது…', nav_today:'இன்று', nav_farm:'என் பண்ணை', nav_help:'பயிர் பராமரிப்பு', nav_resources:'பண்ணை சேவைகள்', nav_groups:'ஒன்றாக', nav_market:'சந்தை', nav_planner:'ஸ்மார்ட் பண்ணை திட்டம்' },
};
Object.assign(translations.en, { nav_input_guard: 'Input Guard' });
Object.assign(translations.ml, { nav_input_guard: 'ഇൻപുട്ട് ഗാർഡ്' });
Object.assign(translations.hi, { nav_input_guard: 'इनपुट गार्ड' });
Object.assign(translations.ta, { nav_input_guard: 'உள்ளீடு சரிபார்' });
export const cropLabels = {
  en: { banana:'Banana', coconut:'Coconut', paddy:'Paddy', pepper:'Pepper', tomato:'Tomato', onion:'Onion', potato:'Potato', arecanut:'Arecanut', rubber:'Rubber', ginger:'Ginger', turmeric:'Turmeric', vegetables:'Vegetables' },
  ml: { banana:'വാഴപ്പഴം', coconut:'തേങ്ങ', paddy:'നെല്ല്', pepper:'കുരുമുളക്', tomato:'തക്കാളി', onion:'ഉള്ളി', potato:'ഉരുളക്കിഴങ്ങ്', arecanut:'അടയ്ക്ക', rubber:'റബ്ബർ', ginger:'ഇഞ്ചി', turmeric:'മഞ്ഞൾ', vegetables:'പച്ചക്കറികൾ' },
  hi: { banana:'केला', coconut:'नारियल', paddy:'धान', pepper:'काली मिर्च', tomato:'टमाटर', onion:'प्याज', potato:'आलू', arecanut:'सुपारी', rubber:'रबर', ginger:'अदरक', turmeric:'हल्दी', vegetables:'सब्जियां' },
  ta: { banana:'வாழை', coconut:'தேங்காய்', paddy:'நெல்', pepper:'மிளகு', tomato:'தக்காளி', onion:'வெங்காயம்', potato:'உருளைக்கிழங்கு', arecanut:'பாக்கு', rubber:'ரப்பர்', ginger:'இஞ்சி', turmeric:'மஞ்சள்', vegetables:'காய்கறிகள்' },
};
